collections:
  - slides

# Over-ridden for publish with `_publish.yml`
baseurl: ""
url: ""

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: false
  parse_block_html: true
  parse_span_html: true

exclude:
  - README.md
  - docs
